# Generated by Django 5.1 on 2024-09-14 17:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('affiliates', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.agent'),
        ),
        migrations.AddField(
            model_name='contract',
            name='affiliate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.affiliate'),
        ),
        migrations.AddField(
            model_name='contract',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.client'),
        ),
        migrations.AddField(
            model_name='contract',
            name='insurance_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='affiliates.insuranceobject'),
        ),
        migrations.AddField(
            model_name='insurancerisk',
            name='insurance_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliates.insuranceobject'),
        ),
        migrations.AddField(
            model_name='contract',
            name='insurance_risk',
            field=models.ManyToManyField(to='affiliates.insurancerisk'),
        ),
        migrations.AddField(
            model_name='insuranceobject',
            name='insurance_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='affiliates.insurancetype'),
        ),
        migrations.AddField(
            model_name='contract',
            name='insurance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='affiliates.insurancetype'),
        ),
        migrations.AddField(
            model_name='policy',
            name='agent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.agent'),
        ),
        migrations.AddField(
            model_name='policy',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='affiliates.contract'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='affiliates.question'),
        ),
    ]
