# Generated by Django 5.1 on 2024-09-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='gurantee',
            field=models.IntegerField(default=1),
        ),
    ]
