# Generated by Django 5.1 on 2024-09-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancetype',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
