# Generated by Django 5.1 on 2024-09-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0003_alter_insurancetype_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='company_history',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
