# Generated by Django 5.1 on 2024-09-16 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0003_contract_gurantee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='gurantee',
            new_name='guarantee',
        ),
    ]
