# Generated by Django 5.1 on 2024-09-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0004_rename_gurantee_contract_guarantee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_history',
            field=models.TextField(),
        ),
    ]
