# Generated by Django 5.1 on 2024-09-15 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0004_companypartners_company_company_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancerisk',
            name='insurance_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_objects', to='affiliates.insuranceobject'),
        ),
    ]
