# Generated by Django 5.1 on 2024-09-18 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0005_alter_company_company_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='history',
            field=models.JSONField(default=None, null=True),
        ),
    ]
