# Generated by Django 5.1 on 2024-09-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('affiliates', '0005_alter_insurancerisk_insurance_object'),
    ]

    operations = [
        migrations.AddField(
            model_name='insurancetype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
